"use client";

import { useState, useEffect } from "react";
import Link from "next/link";
import {
  FileText, CheckCircle, Clock, Calendar, Loader2, Zap, FileDown, Search, X, Info,
  Activity, Users, TrendingUp, ChevronRight, Award, Target, LayoutDashboard,
  ArrowUpRight, ShieldAlert, BarChart3, Fingerprint, BrainCircuit, AlertOctagon,
  Sparkles, ArrowDownRight, Bot, MousePointer2, Network, Cpu, Database,
  TrendingDown, ShieldCheck, PieChart as PieIcon, LineChart as LineIcon,
  MessageSquare, Lightbulb, FileCheck, History, Palette, Type, AlignLeft,
  ListChecks, Settings2, PenLine, FilePlus, ChevronDown, Check, Layers, Monitor, Shield,
  Trophy, ZapOff, Timer
} from "lucide-react";
import {
  getReportKpisAction,
  logReportGenerationAction,
  getReportHistoryAction
} from "@/app/actions/admin-actions";
import { clsx } from "clsx";

// Date ranges removed as we're using a custom date picker

const TEMPLATES = [
  { id: "exec", name: "Executive Summary", desc: "High-level summary for management." },
  { id: "ops", name: "Detailed Operations", desc: "Full logs and metric distributions." },
  { id: "tech", name: "AI Performance", desc: "Focus on AI accuracy and automation." },
  { id: "weekly", name: "Weekly Review", desc: "Performance tracking for team meetings." }
];

const loadJsPDF = () => {
  return new Promise((resolve) => {
    if ((window as any).jspdf) return resolve((window as any).jspdf);
    const script = document.createElement("script");
    script.src = "https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js";
    script.onload = () => resolve((window as any).jspdf);
    document.head.appendChild(script);
  });
};

const buildPdfDocument = async (formData: any, metrics: any, kpis: any) => {
  const jspdfModule: any = await loadJsPDF();
  const { jsPDF } = jspdfModule;
  const doc = new jsPDF();
  const themeColor = formData.theme === "Professional" ? [79, 70, 229] : [16, 185, 129];

  // PAGE 1: COVER
  doc.setFillColor(themeColor[0], themeColor[1], themeColor[2]);
  doc.rect(0, 0, 210, 297, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(50); doc.text("FORS", 105, 90, { align: "center" });
  doc.setFontSize(14); doc.text("SYSTEM REPORT", 105, 100, { align: "center" });
  doc.setDrawColor(255, 255, 255); doc.line(80, 105, 130, 105);
  doc.setFontSize(28); doc.text(formData.name.toUpperCase(), 105, 160, { align: "center", maxWidth: 160 });
  doc.setFontSize(10); doc.text(`GENERATED BY SYSTEM ON ${new Date().toLocaleDateString()}`, 105, 260, { align: "center" });

  // PAGE 2: DASHBOARD
  doc.addPage();
  doc.setFillColor(themeColor[0], themeColor[1], themeColor[2]);
  doc.rect(0, 0, 210, 25, "F");
  doc.setTextColor(255, 255, 255); doc.setFontSize(12); doc.text("EXECUTIVE PERFORMANCE DASHBOARD", 20, 16);

  let y = 45;
  doc.setTextColor(30, 41, 59); doc.setFontSize(18); doc.text("OPERATIONAL TELEMETRY", 20, y);
  y += 10;
  doc.setTextColor(100, 116, 139); doc.setFontSize(9); doc.text(doc.splitTextToSize(formData.description || "", 170), 20, y);
  y += 20;

  const activeMetrics: { label: string; val: string; sub: string; }[] = [];
  if (metrics.reliability) activeMetrics.push({ label: "RELIABILITY INDEX", val: `${kpis.totalTickets > 0 ? Math.round((kpis.closedTickets / kpis.totalTickets) * 100) : 0}%`, sub: "Resolution Velocity" });
  if (metrics.aiAccuracy) activeMetrics.push({ label: "AI CONFIDENCE", val: `${kpis.avgAiConfidence}%`, sub: "Model Accuracy" });
  if (metrics.efficiency) activeMetrics.push({ label: "AUTOMATION RATE", val: `${kpis.sqlProposedTickets}`, sub: "SQL Generation" });
  if (metrics.incidentVolume) activeMetrics.push({ label: "INCIDENT VOLUME", val: `${kpis.totalTickets}`, sub: "Total Tickets" });

  activeMetrics.forEach((m, idx) => {
    doc.setFillColor(248, 250, 252); doc.roundedRect(20, y, 170, 22, 3, 3, "F");
    doc.setTextColor(100, 116, 139); doc.setFontSize(7); doc.text(m.label, 28, y + 8);
    doc.setTextColor(themeColor[0], themeColor[1], themeColor[2]); doc.setFontSize(13); doc.text(m.val, 28, y + 16);
    doc.setTextColor(148, 163, 184); doc.setFontSize(7); doc.text(m.sub, 100, y + 13);
    y += 26;
  });

  if (formData.notes) {
    doc.addPage();
    doc.setFillColor(themeColor[0], themeColor[1], themeColor[2]);
    doc.rect(0, 0, 210, 25, "F");
    doc.setTextColor(255, 255, 255); doc.setFontSize(12); doc.text("EXECUTIVE NARRATIVES", 20, 16);
    y = 45;
    doc.setTextColor(30, 41, 59); doc.setFontSize(18); doc.text("MANAGEMENT OBSERVATIONS", 20, y);
    y += 15;
    doc.setTextColor(71, 85, 105); doc.setFontSize(10);
    doc.text(doc.splitTextToSize(formData.notes, 170), 20, y);
  }

  return doc;
};

export default function ReportPage() {
  const [dateFrom, setDateFrom] = useState<string>("");
  const [dateTo, setDateTo] = useState<string>("");
  const [kpis, setKpis] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [showPdfConfig, setShowPdfConfig] = useState(false);
  const [history, setHistory] = useState<any[]>([]);

  const [downloadingId, setDownloadingId] = useState<string | null>(null);
  const [previewPdf, setPreviewPdf] = useState<{ url: string, doc: any, name: string } | null>(null);

  const loadData = async () => {
    setLoading(true);
    try {
      const [data, hist] = await Promise.all([
        getReportKpisAction(dateFrom || undefined, dateTo || undefined),
        getReportHistoryAction()
      ]);
      setKpis(data);
      setHistory(hist);
    } catch (e) {
      console.error("Failed to load report data", e);
    }
    setLoading(false);
  };

  const handleDownloadHistoricalReport = async (log: any) => {
    if (downloadingId) return; // Prevent multiple clicks
    setDownloadingId(log.id);
    const formData = {
      name: log.reportName || "Historical_Report",
      description: log.reportDescription || "",
      theme: log.reportTheme || "Professional",
      notes: log.reportConfig?.notes || ""
    };
    const metrics = log.reportConfig?.metrics || {};
    try {
      const doc = await buildPdfDocument(formData, metrics, kpis);
      const url = doc.output('bloburl');
      setPreviewPdf({ url, doc, name: formData.name });
    } catch (e) {
      console.error("Failed to download historical report", e);
    }
    setDownloadingId(null);
  };

  useEffect(() => {
    loadData();
  }, [dateFrom, dateTo]);

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-[80vh] bg-[#F8F9FF]">
        <div className="relative">
          <Loader2 className="w-10 h-10 text-indigo-500 animate-spin" />
          <div className="absolute inset-0 blur-2xl bg-indigo-500/20 animate-pulse" />
        </div>
      </div>
    );
  }

  if (!kpis) return null;

  const resRate = kpis.totalTickets > 0 ? Math.round((kpis.closedTickets / kpis.totalTickets) * 100) : 0;
  const topTeam = (kpis.teamDistribution || []).sort((a: any, b: any) => b.c - a.c)[0]?.team || "N/A";

  return (
    <div className="min-h-screen bg-transparent px-4 sm:px-6 pb-20 space-y-6 font-sans selection:bg-indigo-100 w-full relative overflow-y-auto">

      <div className="absolute top-0 right-0 w-[40rem] h-[40rem] bg-indigo-500/5 rounded-full blur-[100px] -mr-48 -mt-48 animate-pulse pointer-events-none" />
      <div className="absolute bottom-0 left-0 w-[30rem] h-[30rem] bg-fuchsia-500/5 rounded-full blur-[80px] -ml-32 -mb-32 animate-pulse delay-700 pointer-events-none" />

      <header className="relative z-10 flex flex-col sm:flex-row sm:items-center justify-between gap-4 animate-in fade-in slide-in-from-top-2 duration-500 px-1">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-indigo-500 to-violet-600 flex items-center justify-center shadow-lg shadow-indigo-100 shrink-0 transform hover:rotate-6 transition-transform">
            <Activity className="w-5 h-5 text-white" />
          </div>
          <div>
            <h1 className="text-lg font-black text-slate-800 tracking-tight">
              Over<span className="text-indigo-500">view</span>
            </h1>
            <p className="text-[9px] font-bold text-slate-400 uppercase tracking-widest mt-1 whitespace-nowrap">Monitor system performance and generate reports.</p>
          </div>
        </div>

        <div className="flex items-center gap-1.5">
          <div className="bg-white border border-slate-200 p-1 rounded-xl shadow-sm flex items-center gap-1.5 scale-[0.95] sm:scale-100 origin-right">
            <button
              onClick={() => { setDateFrom(""); setDateTo(""); }}
              className={clsx(
                "px-2 py-1 rounded-md text-[8px] font-black uppercase tracking-widest transition-all whitespace-nowrap",
                (!dateFrom && !dateTo) ? "bg-slate-900 text-white shadow-md" : "text-slate-400 hover:text-indigo-600 hover:bg-slate-50"
              )}
            >
              All Time
            </button>
            <div className="w-px h-3 bg-slate-200 mx-0.5"></div>
            <span className="text-[9px] font-black text-slate-400 uppercase tracking-widest">From</span>
            <input
              type="date"
              value={dateFrom}
              onChange={(e) => setDateFrom(e.target.value)}
              className="text-[10px] font-bold bg-slate-50 border border-slate-200 rounded-md text-slate-600 px-1.5 py-1 outline-none focus:border-indigo-400 transition-all w-[100px]"
            />
            <span className="text-[9px] font-black text-slate-400 uppercase tracking-widest">To</span>
            <input
              type="date"
              value={dateTo}
              onChange={(e) => setDateTo(e.target.value)}
              className="text-[10px] font-bold bg-slate-50 border border-slate-200 rounded-md text-slate-600 px-1.5 py-1 outline-none focus:border-indigo-400 transition-all w-[100px]"
            />
          </div>
          <button
            onClick={() => setShowPdfConfig(true)}
            className="h-9 px-4 bg-slate-900 text-white rounded-xl flex items-center gap-2 font-black text-[9px] uppercase tracking-[0.1em] hover:bg-indigo-600 transition-all shadow-lg border border-slate-800 active:scale-95 group shrink-0"
          >
            <FileDown className="w-3.5 h-3.5 text-indigo-400 group-hover:text-white transition-colors" />
            <span className="whitespace-nowrap">Generate Report</span>
          </button>
        </div>
      </header>

      <div className="relative z-10 grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
        <SmallInsightCard icon={FileText} label="Total Tickets" value={kpis.totalTickets} trend="All" sub="All recorded tickets" color="indigo" delay={0} />
        <SmallInsightCard icon={CheckCircle} label="Solved Tickets" value={kpis.closedTickets} trend={`${resRate}%`} sub="Closed & Validated" color="emerald" delay={50} />
        <SmallInsightCard icon={Clock} label="Pending Tickets" value={kpis.pendingTickets} trend="Active" sub="Awaiting resolution" color="amber" delay={100} />
        <SmallInsightCard icon={Zap} label="AI Proposed" value={kpis.sqlProposedTickets} trend="AI" sub="Solutions suggested" color="blue" delay={150} />
        <SmallInsightCard icon={ShieldCheck} label="Validated" value={kpis.validatedTickets} trend="Approved" sub="AI solutions accepted" color="emerald" delay={200} />
        <SmallInsightCard icon={AlertOctagon} label="Rejected" value={kpis.rejectedTickets} trend="Declined" sub="AI solutions rejected" color="rose" delay={250} />
        <SmallInsightCard icon={ZapOff} label="Canceled" value={kpis.canceledTickets} trend="Canceled" sub="Closed without resolution" color="cyan" delay={300} />
        <SmallInsightCard icon={BrainCircuit} label="AI Confidence" value={`${kpis.avgAiConfidence}%`} trend="Average" sub="Model certainty score" color="fuchsia" delay={350} />
      </div>

      <div className="relative z-10 grid grid-cols-12 gap-5">
        <div className="col-span-12">
          <div className="bg-white rounded-2xl border border-slate-100 p-5 shadow-sm h-full flex flex-col">
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center gap-2">
                <div className="w-8 h-8 rounded-lg bg-indigo-50 flex items-center justify-center">
                  <History className="w-4 h-4 text-indigo-500" />
                </div>
                <h3 className="text-sm font-black text-slate-800">Generation History</h3>
              </div>
              <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Traceability Log</p>
            </div>

            <div className="flex-1 space-y-2 overflow-y-auto max-h-[300px] pr-2 scrollbar-hide">
              {history.length === 0 ? (
                <div className="flex flex-col items-center justify-center py-10 text-slate-300">
                  <FileText className="w-10 h-10 mb-2 opacity-20" />
                  <p className="text-xs font-bold italic">No reports generated yet</p>
                </div>
              ) : (
                history.map((log: any) => (
                  <div key={log.id} onClick={() => handleDownloadHistoricalReport(log)} className="flex items-center justify-between p-3 rounded-xl bg-slate-50 border border-slate-100 group hover:border-indigo-200 hover:bg-indigo-50/30 transition-all cursor-pointer">
                    <div className="flex items-center gap-3">
                      <div className={clsx(
                        "w-8 h-8 rounded-lg flex items-center justify-center shrink-0 border shadow-sm",
                        log.reportTheme === "Executive" || log.reportTheme === "Professional" ? "bg-indigo-100 text-indigo-600 border-indigo-200" :
                          log.reportTheme === "Technical" || log.reportTheme === "Analytical" ? "bg-emerald-100 text-emerald-600 border-emerald-200" :
                            "bg-slate-100 text-slate-600 border-slate-200"
                      )}>
                        {downloadingId === log.id ? <Loader2 className="w-4 h-4 animate-spin" /> : <FileDown className="w-4 h-4 opacity-50 group-hover:opacity-100 transition-opacity" />}
                      </div>
                      <div>
                        <p className="text-xs font-black text-slate-800 leading-tight">{log.reportName || "Untitled Report"}</p>
                        <p className="text-[10px] font-medium text-slate-400 leading-tight mt-0.5 truncate max-w-[200px]">{log.reportDescription || "No description provided"}</p>
                      </div>
                    </div>
                    <div className="text-right flex flex-col items-end">
                      <p className="text-[9px] font-black text-slate-400 uppercase tracking-widest">{new Date(log.created_at).toLocaleDateString()}</p>
                      <p className="text-[8px] font-bold text-slate-300 uppercase mt-0.5">{log.userMatricule}</p>
                    </div>
                  </div>
                ))
              )}
            </div>
          </div>
        </div>
      </div>

      {showPdfConfig && (
        <PdfConfigModal onClose={() => { setShowPdfConfig(false); loadData(); }} kpis={kpis} onPreviewReady={(doc: any, name: string) => {
          setShowPdfConfig(false);
          setPreviewPdf({ url: doc.output('bloburl'), doc, name });
          loadData();
        }} />
      )}

      {previewPdf && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-6">
          <div className="fixed inset-0 bg-slate-900/80 backdrop-blur-sm animate-in fade-in" onClick={() => setPreviewPdf(null)} />
          <div className="relative bg-white w-full max-w-5xl h-[90vh] rounded-[2rem] shadow-2xl flex flex-col overflow-hidden animate-in zoom-in-95">
            <div className="flex items-center justify-between p-4 border-b bg-slate-50">
              <h3 className="font-bold text-slate-800">{previewPdf.name}.pdf</h3>
              <div className="flex items-center gap-2">
                <button onClick={() => {
                  const safeName = previewPdf.name.replace(/[^a-zA-Z0-9_-]/g, '_');
                  previewPdf.doc.save(`${safeName}.pdf`);
                }} className="px-4 py-2 bg-indigo-600 hover:bg-indigo-700 text-white text-xs font-black tracking-widest uppercase rounded-xl flex items-center gap-2 transition-colors shadow-lg shadow-indigo-200">
                  <FileDown className="w-4 h-4" /> Download PDF
                </button>
                <button onClick={() => setPreviewPdf(null)} className="p-2 text-slate-400 hover:text-slate-600 bg-white border border-slate-200 rounded-xl transition-colors">
                  <X className="w-5 h-5" />
                </button>
              </div>
            </div>
            <iframe src={previewPdf.url} className="w-full flex-1 border-none bg-slate-100" title="PDF Preview" />
          </div>
        </div>
      )}
    </div>
  );
}

function SmallInsightCard({ icon: Icon, label, value, trend, sub, color, delay }: any) {
  const themes: any = {
    indigo: "from-indigo-500 to-indigo-600 text-indigo-600 bg-indigo-50 border-indigo-100",
    blue: "from-blue-500 to-blue-600 text-blue-600 bg-blue-50 border-blue-100",
    amber: "from-amber-500 to-amber-600 text-amber-600 bg-amber-50 border-amber-100",
    fuchsia: "from-fuchsia-500 to-fuchsia-600 text-fuchsia-600 bg-fuchsia-50 border-fuchsia-100",
    rose: "from-rose-500 to-rose-600 text-rose-600 bg-rose-50 border-rose-100",
    cyan: "from-cyan-500 to-cyan-600 text-cyan-600 bg-cyan-50 border-cyan-100",
    emerald: "from-emerald-500 to-emerald-600 text-emerald-600 bg-emerald-50 border-emerald-100",
  };
  const theme = themes[color] || themes.indigo;
  const colors = theme.split(' ');

  return (
    <div style={{ animationDelay: `${delay}ms` }} className="bg-white rounded-2xl border border-slate-100 p-4 shadow-sm hover:shadow-lg hover:-translate-y-1 transition-all duration-300 group flex flex-col h-full min-h-[120px] animate-in fade-in slide-in-from-bottom-2 fill-mode-both">
      <div className="flex items-center justify-between mb-3">
        <div className={clsx("w-9 h-9 rounded-xl flex items-center justify-center shrink-0 shadow-sm bg-gradient-to-br", colors[0], colors[1])}>
          <Icon className="w-4.5 h-4.5 text-white" />
        </div>
        <div className={clsx("px-1.5 py-0.5 rounded-lg text-[8px] font-black uppercase tracking-widest", colors[3], colors[4])}>
          {trend}
        </div>
      </div>
      <div className="space-y-0.5 mt-auto">
        <p className="text-[8px] font-black text-slate-400 uppercase tracking-widest leading-none">{label}</p>
        <p className={clsx("text-lg font-black tracking-tight leading-none bg-clip-text text-transparent bg-gradient-to-r", colors[0], colors[1])}>{value}</p>
        <p className="text-[9px] font-medium text-slate-400 leading-tight italic truncate">"{sub}"</p>
      </div>
    </div>
  );
}

function ActionTile({ icon: Icon, title, desc, link, color }: any) {
  return (
    <Link href={link} className="block group">
      <div className="bg-white rounded-2xl border border-slate-100 p-4 shadow-sm hover:shadow-lg hover:-translate-y-1 transition-all duration-300 flex items-center gap-4 relative overflow-hidden">
        <div className={clsx("w-10 h-10 rounded-xl bg-slate-50 flex items-center justify-center shrink-0 group-hover:bg-slate-900 group-hover:text-white transition-all shadow-inner")}>
          <Icon className="w-5 h-5" />
        </div>
        <div className="flex-1 space-y-0.5">
          <h4 className="text-xs font-black text-slate-800">{title}</h4>
          <p className="text-[10px] font-medium text-slate-400 leading-tight">{desc}</p>
        </div>
        <ChevronRight className="w-4 h-4 text-indigo-600 transition-transform group-hover:translate-x-0.5" />
      </div>
    </Link>
  );
}

function PdfConfigModal({ onClose, kpis, onPreviewReady }: any) {
  const [step, setStep] = useState<"form" | "generating" | "success">("form");
  const [formData, setFormData] = useState({
    name: `Report_${new Date().toLocaleDateString().replace(/\//g, '-')}`,
    description: "Operational Synthesis & Strategic IT Report.",
    theme: "Professional",
    template: "exec",
    notes: "",
  });
  const [metrics, setMetrics] = useState({
    reliability: true,
    efficiency: true,
    aiAccuracy: true,
    workload: true,
    slaCompliance: true,
    incidentVolume: true,
    teamDistribution: false
  });

  const handleTemplateChange = (tid: string) => {
    const t = TEMPLATES.find(x => x.id === tid);
    if (!t) return;
    setFormData(prev => ({ ...prev, template: tid, name: `FORS_${t.name.replace(/\s+/g, '_')}_${new Date().toLocaleDateString().replace(/\//g, '-')}` }));
    if (tid === "exec") setMetrics({ reliability: true, efficiency: true, aiAccuracy: true, workload: false, slaCompliance: true, incidentVolume: false, teamDistribution: false });
    if (tid === "ops") setMetrics({ reliability: true, efficiency: true, aiAccuracy: true, workload: true, slaCompliance: true, incidentVolume: true, teamDistribution: true });
    if (tid === "tech") setMetrics({ reliability: true, efficiency: false, aiAccuracy: true, workload: true, slaCompliance: false, incidentVolume: true, teamDistribution: false });
  };

  const handleGenerate = async () => {
    setStep("generating");
    await logReportGenerationAction({ name: formData.name, description: formData.description, theme: formData.theme, config: { metrics, notes: formData.notes } });
    try {
      const doc = await buildPdfDocument(formData, metrics, kpis);
      setTimeout(() => {
        onPreviewReady(doc, formData.name);
      }, 1200);
    } catch (e) { setStep("success"); }
  };

  return (
    <div className="fixed inset-0 z-20 flex items-center justify-center p-6">
      <div className="fixed inset-0 bg-slate-900/60 backdrop-blur-md animate-in fade-in duration-300" onClick={onClose} />

      <div className="relative bg-white w-full max-w-xl rounded-[3rem] shadow-[0_50px_100px_-20px_rgba(0,0,0,0.6)] overflow-hidden animate-in zoom-in-95 duration-200 flex flex-col border border-white/20">
        {step === "form" && (
          <div className="flex flex-col h-full max-h-[85vh]">
            <div className="p-8 border-b border-white/10 bg-gradient-to-br from-slate-900 via-indigo-950 to-indigo-900 relative shrink-0">
              <div className="absolute top-0 right-0 w-48 h-48 bg-indigo-500/20 rounded-full blur-3xl -mr-24 -mt-24 animate-pulse" />
              <div className="relative z-10 flex justify-between items-center">
                <div>
                  <h3 className="text-2xl font-black text-white tracking-tight leading-none">Report Generator</h3>
                  <p className="text-[10px] font-bold text-indigo-400 uppercase tracking-[0.2em] mt-3">Report Configuration</p>
                </div>
                <button onClick={onClose} className="w-10 h-10 bg-white/5 hover:bg-white/10 border border-white/10 flex items-center justify-center rounded-xl transition-all text-white/50 hover:text-white"><X className="w-5 h-5" /></button>
              </div>
            </div>

            <div className="flex-1 p-8 space-y-8 overflow-y-auto scrollbar-hide bg-slate-50/50">
              {/* Template Selector */}
              <div className="space-y-3">
                <label className="text-[11px] font-black text-slate-400 uppercase tracking-widest flex items-center gap-2"><Trophy className="w-4 h-4 text-amber-500" /> Report Template</label>
                <div className="grid grid-cols-2 gap-3">
                  {TEMPLATES.map(t => (
                    <button key={t.id} onClick={() => handleTemplateChange(t.id)} className={clsx("p-4 rounded-2xl border-2 transition-all text-left group", formData.template === t.id ? "bg-white border-indigo-500 shadow-xl" : "bg-white/60 border-transparent hover:border-slate-200")}>
                      <p className={clsx("text-xs font-black uppercase tracking-widest", formData.template === t.id ? "text-indigo-600" : "text-slate-700")}>{t.name}</p>
                      <p className="text-[9px] font-medium text-slate-400 mt-1 line-clamp-1">{t.desc}</p>
                    </button>
                  ))}
                </div>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <label className="text-[11px] font-black text-slate-400 uppercase tracking-widest flex items-center gap-2"><Type className="w-4 h-4 text-indigo-500" /> Report Name</label>
                  <input type="text" className="w-full px-5 py-4 bg-white border border-slate-200/60 rounded-2xl text-xs font-bold outline-none focus:ring-4 focus:ring-indigo-100 transition-all shadow-sm" value={formData.name} onChange={e => setFormData(prev => ({ ...prev, name: e.target.value }))} />
                </div>
                <div className="space-y-2">
                  <label className="text-[11px] font-black text-slate-400 uppercase tracking-widest flex items-center gap-2"><Palette className="w-4 h-4 text-rose-500" /> Theme</label>
                  <div className="flex gap-2 p-1.5 bg-white border border-slate-200/60 rounded-2xl shadow-sm">
                    {["Professional", "Analytical"].map(t => (
                      <button key={t} onClick={() => setFormData(prev => ({ ...prev, theme: t }))} className={clsx("flex-1 py-2.5 rounded-xl text-[9px] font-black uppercase tracking-widest transition-all", formData.theme === t ? "bg-slate-900 text-white shadow-lg" : "text-slate-400 hover:bg-slate-50")}>{t}</button>
                    ))}
                  </div>
                </div>
              </div>

              <div className="space-y-3">
                <label className="text-[11px] font-black text-slate-400 uppercase tracking-widest flex items-center gap-2"><BarChart3 className="w-4 h-4 text-violet-500" /> Metrics to Include</label>
                <div className="grid grid-cols-2 gap-3">
                  {Object.entries(metrics).map(([key, val]) => (
                    <button key={key} onClick={() => setMetrics(prev => ({ ...prev, [key]: !val }))} className={clsx("p-4 rounded-2xl border transition-all flex items-center justify-between group", val ? "bg-white border-indigo-200 text-indigo-600 shadow-lg ring-2 ring-indigo-50" : "bg-white/40 border-slate-100 text-slate-400")}>
                      <div className="flex items-center gap-3">
                        <div className={clsx("w-6 h-6 rounded-lg flex items-center justify-center transition-all", val ? "bg-indigo-500 text-white shadow-lg" : "bg-slate-100 text-slate-300")}>
                          {val ? <Check className="w-3.5 h-3.5" /> : <ChevronDown className="w-3 h-3" />}
                        </div>
                        <p className="text-[9px] font-black uppercase tracking-widest">{key.replace(/([A-Z])/g, ' $1')}</p>
                      </div>
                    </button>
                  ))}
                </div>
              </div>

              <div className="space-y-3">
                <label className="text-[11px] font-black text-slate-400 uppercase tracking-widest flex items-center gap-2"><PenLine className="w-4 h-4 text-amber-500" /> Custom Notes</label>
                <textarea className="w-full px-5 py-4 bg-white border border-slate-200/60 rounded-2xl text-xs font-bold h-32 resize-none outline-none focus:ring-4 focus:ring-indigo-100 transition-all shadow-sm" value={formData.notes} onChange={e => setFormData(prev => ({ ...prev, notes: e.target.value }))} placeholder="Add custom notes or comments..." />
              </div>
            </div>

            <div className="p-8 bg-white border-t border-slate-100 shrink-0">
              <button onClick={handleGenerate} className="w-full py-5 bg-slate-900 text-white rounded-[2.5rem] font-black uppercase tracking-widest text-xs shadow-[0_30px_60px_-15px_rgba(0,0,0,0.4)] hover:bg-black hover:-translate-y-1 transition-all flex items-center justify-center gap-4 border-b-4 border-slate-700">
                <FileDown className="w-6 h-6 text-indigo-400" /> Generate Report
              </button>
            </div>
          </div>
        )}
        {step === "generating" && (<div className="p-24 flex flex-col items-center text-center space-y-6"><Loader2 className="w-16 h-16 text-indigo-600 animate-spin" /><h3 className="text-xl font-black text-slate-800 tracking-tight">Generating Report...</h3><p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Integrating selected metrics</p></div>)}
        {step === "success" && (<div className="p-24 flex flex-col items-center text-center space-y-8 animate-in zoom-in-95"><FileCheck className="w-24 h-24 text-emerald-500" /><h3 className="text-2xl font-black text-slate-800 tracking-tight">Report Generated</h3><button onClick={onClose} className="w-full py-5 bg-emerald-500 text-white rounded-[2rem] font-black uppercase tracking-widest text-[10px] shadow-xl">Back to Overview</button></div>)}
      </div>
    </div>
  );
}
